[package]
name = "math-rust-lib"
version = "0.2.0"
edition = "2024"
license = "MIT"
repository="https://github.com/GOH23/math-rust-lib"
[lib]
crate-type = ["cdylib"]
[dependencies]
js-sys = "0.3.83"
wasm-bindgen = "0.2.106"
